### ISSUE TITLE
How to use get_glyph_for_action_origin

### ISSUE THREAD

**Issue by codingMASTER398** [Noxime/steamworks-rs#208]
Writing this, I'm extremely new to Rust, but I have no clue how you could possibly use get_glyph_for_action_origin in the input API. One of the required parameters is a "EInputActionOrigin", but the enum behind that is private.

How would you interact with this API?

**Comment by Noxime** [comment]
`EInputActionOrigin` is public, but it's part of the steamworks-sys crate. You must also include it in your dependencies. I think we should re-export it at crate level for convenience.

```toml
steamworks = { git = "https://github.com/Noxime/steamworks-rs" }
steamworks-sys = { git = "https://github.com/Noxime/steamworks-rs" }
```

```rs
use steamworks_sys::EInputActionOrigin;
...
let glyph = input.get_glyph_for_action_origin(EInputActionOrigin::k_EInputActionOrigin_SteamController_A);
```
